[package]
name = "zf"
version = "0.1.2"
edition = "2021"
description = "a task runner"
license = "MIT"
repository = "https://github.com/callum-oakley/zf"

[dependencies]
anyhow = "1.0.86"
regex = "1.10.5"
termcolor = "1.4.1"
